from loader import load, log, player_cards
from code_parser import format

_error_str = """
Mismatch #{count}:

Card: {name}

Autogenerated text:
{code}

Expected value:
{text}
"""

def test_autogenerated_text():
    count = 0
    for cards in player_cards.values():
        for card in cards:
            code = format(card["code"][0], "PE", card["name"], card["type"])
            if code and code != card["text"]:
                count += 1
                log(_error_str.format(count=count, name=card["name"], code=code, text=card["text"]), level="error")
            special = format(card["code"][1], "PS", card["name"], card["type"])[0]
            if special and special != card["special"]:
                count += 1
                log(_error_str.format(count=count, name=card["name"], code=special, text=card["special"]), level="error")

if __name__ == "__main__":
    load()
    test_autogenerated_text()
